name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: gregor
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            eval $(ssh-agent -s)
            ssh-add /home/gregor/.ssh/github_deploy
            cd /home/gregor/armadion-front-nux 
            sudo git pull 
            sudo npm ci 
            sudo npm run build 
            pm2 restart index
